version: '2' 
services:
  mainnet_fork_node:    
    build: ./
    ports:
     - "8546:8546"
     - "8545:8545"       
     - "8180:8180"
    restart: always     
    volumes:
     - /var/lib/docker/volumes/backend_parity_data/_data/chains/ethereum:/var/parity/chains/foundation-fork/
