version: '2' 
services:
  mainnet_fork_node_rust:    
    image: neufund/parity-foundation-fork-rust
    ports:
     - "8546:8546"
     - "8545:8545"
     - "30303:30303"
    restart: always     
    volumes:
     - /var/lib/docker/volumes/backend_parity_data/_data/chains/ethereum:/var/parity/chains/foundation-fork/
